"""Focused regression tests for complete-ops.py.

Covers the complete-ops.py CLI contract:
  - check-preconditions
  - finalize (dry-run and execute)
  - archive-status
  - archive boundary assertions (CP-2)
  - confirmation gate (CP-10)

All tests use fixture data — no real governance repo is accessed.

Run: $PYTHON -m pytest _bmad/lens-work/skills/lens-complete/scripts/tests/test-complete-ops.py -q
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

import pytest
import sys

_LENS_YAML_PATH = next(
    (parent / "scripts" / "lens_yaml.py" for parent in Path(__file__).resolve().parents if (parent / "scripts" / "lens_yaml.py").is_file()),
    None,
)
if _LENS_YAML_PATH is None:
    raise ModuleNotFoundError("lens_yaml")
_LENS_YAML_SPEC = importlib.util.spec_from_file_location("lens_yaml", _LENS_YAML_PATH)
if _LENS_YAML_SPEC is None or _LENS_YAML_SPEC.loader is None:
    raise ModuleNotFoundError("lens_yaml")
yaml = importlib.util.module_from_spec(_LENS_YAML_SPEC)
_LENS_YAML_SPEC.loader.exec_module(yaml)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ALLOWED_WRITE_FILES = {"feature.yaml", "feature-index.yaml", "summary.md"}


# ---------------------------------------------------------------------------
# Helpers — invoke complete-ops.py main() directly without subprocess
# ---------------------------------------------------------------------------

def _script_main():
    """Import and return the main() entry point from complete-ops.py."""
    script_path = Path(__file__).resolve().parents[1] / "complete-ops.py"
    spec = importlib.util.spec_from_file_location("complete_ops", script_path)
    assert spec is not None and spec.loader is not None, f"Could not load {script_path}"
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    return mod.main


def _run(argv: list[str], capsys: pytest.CaptureFixture) -> tuple[int, dict[str, Any]]:
    """Run complete-ops main() with argv and return (exit_code, parsed_json_output)."""
    main = _script_main()
    exit_code = main(argv)
    captured = capsys.readouterr()
    result = json.loads(captured.out)
    return exit_code, result


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def gov_pass(tmp_path: Path) -> Path:
    """Governance repo fixture: dev-phase feature with approved retrospective.md."""
    feature_dir = tmp_path / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature"
    feature_dir.mkdir(parents=True)

    (feature_dir / "feature.yaml").write_text(
        "featureId: lens-dev-test-feature\n"
        "domain: lens-dev\n"
        "service: new-codebase\n"
        "phase: dev\n"
        "name: Test Feature\n"
        "track: express\n",
        encoding="utf-8",
    )

    (feature_dir / "retrospective.md").write_text(
        "---\nstatus: approved\n---\n\n# Retrospective\n\nAll good.\n",
        encoding="utf-8",
    )

    # Optional document-project artifact — presence produces status:pass (not warn)
    (feature_dir / "project-documentation.md").write_text(
        "# Project Documentation\n\nGenerated by lens-document-project.\n",
        encoding="utf-8",
    )

    (tmp_path / "feature-index.yaml").write_text(
        "features:\n"
        "- id: lens-dev-test-feature\n"
        "  featureId: lens-dev-test-feature\n"
        "  domain: lens-dev\n"
        "  service: new-codebase\n"
        "  status: dev\n"
        "  updated_at: '2026-01-01T00:00:00Z'\n",
        encoding="utf-8",
    )
    return tmp_path


@pytest.fixture
def gov_no_retro(tmp_path: Path) -> Path:
    """Governance repo fixture: dev-phase feature without retrospective.md."""
    feature_dir = tmp_path / "features" / "lens-dev" / "new-codebase" / "lens-dev-no-retro"
    feature_dir.mkdir(parents=True)

    (feature_dir / "feature.yaml").write_text(
        "featureId: lens-dev-no-retro\ndomain: lens-dev\nservice: new-codebase\nphase: dev\n",
        encoding="utf-8",
    )
    (tmp_path / "feature-index.yaml").write_text(
        "features:\n- id: lens-dev-no-retro\n  status: dev\n",
        encoding="utf-8",
    )
    return tmp_path


@pytest.fixture
def gov_wrong_phase(tmp_path: Path) -> Path:
    """Governance repo fixture: feature in a planning phase."""
    feature_dir = tmp_path / "features" / "lens-dev" / "new-codebase" / "lens-dev-preplan-feature"
    feature_dir.mkdir(parents=True)

    (feature_dir / "feature.yaml").write_text(
        "featureId: lens-dev-preplan-feature\ndomain: lens-dev\nservice: new-codebase\nphase: preplan\n",
        encoding="utf-8",
    )
    (tmp_path / "feature-index.yaml").write_text(
        "features:\n- id: lens-dev-preplan-feature\n  status: preplan\n",
        encoding="utf-8",
    )
    return tmp_path


@pytest.fixture
def gov_already_complete(tmp_path: Path) -> Path:
    """Governance repo fixture: feature already in complete phase."""
    feature_dir = tmp_path / "features" / "lens-dev" / "new-codebase" / "lens-dev-done-feature"
    feature_dir.mkdir(parents=True)

    (feature_dir / "feature.yaml").write_text(
        "featureId: lens-dev-done-feature\n"
        "domain: lens-dev\n"
        "service: new-codebase\n"
        "phase: complete\n"
        "completed_at: '2026-01-01T00:00:00Z'\n",
        encoding="utf-8",
    )
    (tmp_path / "feature-index.yaml").write_text(
        "features:\n- id: lens-dev-done-feature\n  status: archived\n",
        encoding="utf-8",
    )
    return tmp_path


# ---------------------------------------------------------------------------
# CP-1 / CP-4: check-preconditions — pass case
# ---------------------------------------------------------------------------

def test_check_preconditions_pass(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """Feature in dev phase with approved retrospective.md returns status:pass."""
    exit_code, result = _run(
        ["check-preconditions", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature"],
        capsys,
    )
    assert result["status"] == "pass"
    assert result["feature_id"] == "lens-dev-test-feature"
    assert result["retrospective_skipped"] is False
    assert result["blockers"] == []


# ---------------------------------------------------------------------------
# CP-1 / CP-4: check-preconditions — missing retrospective → fail (blocker, not warn)
# ---------------------------------------------------------------------------

def test_check_preconditions_fail_no_retrospective(capsys: pytest.CaptureFixture, gov_no_retro: Path) -> None:
    """Feature in dev phase without retrospective.md returns status:fail (retrospective is a blocker)."""
    exit_code, result = _run(
        ["check-preconditions", "--governance-repo", str(gov_no_retro), "--feature-id", "lens-dev-no-retro"],
        capsys,
    )
    assert result["status"] == "fail"
    # blocker must be retrospective_missing
    error_or_blocker = result.get("error") or result.get("blocker")
    assert error_or_blocker == "retrospective_missing"
    assert exit_code != 0


# ---------------------------------------------------------------------------
# CP-1 / CP-4: check-preconditions — wrong phase → fail
# ---------------------------------------------------------------------------

def test_check_preconditions_fail_wrong_phase(capsys: pytest.CaptureFixture, gov_wrong_phase: Path) -> None:
    """Feature in a non-completable phase returns status:fail."""
    exit_code, result = _run(
        ["check-preconditions", "--governance-repo", str(gov_wrong_phase), "--feature-id", "lens-dev-preplan-feature"],
        capsys,
    )
    assert result["status"] == "fail"
    assert exit_code != 0


# ---------------------------------------------------------------------------
# CP-4: check-preconditions — already complete → fail
# ---------------------------------------------------------------------------

def test_check_preconditions_fail_already_complete(capsys: pytest.CaptureFixture, gov_already_complete: Path) -> None:
    """Feature already in complete/terminal phase returns status:fail."""
    exit_code, result = _run(
        ["check-preconditions", "--governance-repo", str(gov_already_complete), "--feature-id", "lens-dev-done-feature"],
        capsys,
    )
    assert result["status"] == "fail"
    assert exit_code != 0


# ---------------------------------------------------------------------------
# CP-4: all planning phases fail check-preconditions
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("planning_phase", [
    "preplan", "businessplan", "techplan", "finalizeplan", "expressplan",
])
def test_check_preconditions_fails_all_planning_phases(
    capsys: pytest.CaptureFixture, tmp_path: Path, planning_phase: str
) -> None:
    """check-preconditions returns fail for every planning phase."""
    fid = f"lens-dev-{planning_phase}-test"
    feature_dir = tmp_path / "features" / "lens-dev" / "new-codebase" / fid
    feature_dir.mkdir(parents=True)
    (feature_dir / "feature.yaml").write_text(
        f"featureId: {fid}\ndomain: lens-dev\nservice: new-codebase\nphase: {planning_phase}\n",
        encoding="utf-8",
    )
    (tmp_path / "feature-index.yaml").write_text(
        f"features:\n- id: {fid}\n  status: {planning_phase}\n", encoding="utf-8"
    )
    exit_code, result = _run(
        ["check-preconditions", "--governance-repo", str(tmp_path), "--feature-id", fid],
        capsys,
    )
    assert result["status"] == "fail", f"Expected fail for phase {planning_phase}, got {result['status']}"
    assert exit_code != 0


# ---------------------------------------------------------------------------
# CP-1: finalize --dry-run → returns dry_run without writing files
# ---------------------------------------------------------------------------

def test_finalize_dry_run(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize --dry-run returns planned_changes without writing governance files."""
    feature_yaml = gov_pass / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature" / "feature.yaml"
    mtime_before = feature_yaml.stat().st_mtime

    exit_code, result = _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--dry-run"],
        capsys,
    )
    assert result["status"] == "dry_run"
    assert "planned_changes" in result
    assert len(result["planned_changes"]) >= 2

    # feature.yaml must NOT have been modified
    assert feature_yaml.stat().st_mtime == mtime_before, "finalize --dry-run must not modify feature.yaml"


# ---------------------------------------------------------------------------
# CP-1 / CP-5: finalize --confirm → archives feature, writes exactly 3 files
# ---------------------------------------------------------------------------

def test_finalize_archives_feature(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize --confirm sets phase=complete, archives the index, and writes summary.md."""
    exit_code, result = _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--confirm"],
        capsys,
    )
    assert exit_code == 0, f"Expected exit 0, got {exit_code}. Result: {result}"
    assert result["status"] == "complete"
    assert result["feature_id"] == "lens-dev-test-feature"
    assert "archived_at" in result

    # Verify feature.yaml updated
    fp = gov_pass / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature" / "feature.yaml"
    fd = yaml.safe_load(fp.read_text(encoding="utf-8"))
    assert fd["phase"] == "complete"
    assert "completed_at" in fd

    # Verify feature-index.yaml updated
    idx = yaml.safe_load((gov_pass / "feature-index.yaml").read_text(encoding="utf-8"))
    entry = next(e for e in idx["features"] if e["id"] == "lens-dev-test-feature")
    assert entry["status"] == "archived"

    # Verify summary.md written
    summary_path = fp.parent / "summary.md"
    assert summary_path.exists(), "summary.md must be written by finalize"
    assert "archived" in summary_path.read_text(encoding="utf-8").lower()


# ---------------------------------------------------------------------------
# CP-2: archive boundary — finalize writes ONLY the three allowed files
# ---------------------------------------------------------------------------

def test_finalize_only_writes_allowed_files(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize must not write files outside feature.yaml, feature-index.yaml, and summary.md."""
    def _all_files(root: Path) -> set[str]:
        return {str(p.relative_to(root)) for p in root.rglob("*") if p.is_file()}

    before = _all_files(gov_pass)
    _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--confirm"],
        capsys,
    )
    after = _all_files(gov_pass)
    new_files = after - before
    unexpected = {f for f in new_files if Path(f).name not in ALLOWED_WRITE_FILES}
    assert not unexpected, f"finalize wrote unexpected files: {unexpected}"


# ---------------------------------------------------------------------------
# CP-2: finalize must NOT add unexpected YAML keys to feature.yaml
# ---------------------------------------------------------------------------

def test_finalize_does_not_add_new_yaml_keys(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize must not add YAML keys beyond the expected mutation set."""
    fp = gov_pass / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature" / "feature.yaml"
    before_keys = set(yaml.safe_load(fp.read_text(encoding="utf-8")).keys())

    _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--confirm"],
        capsys,
    )

    after_keys = set(yaml.safe_load(fp.read_text(encoding="utf-8")).keys())
    new_keys = after_keys - before_keys
    allowed_new_keys = {"completed_at", "phase_transitions"}
    unexpected = new_keys - allowed_new_keys
    assert not unexpected, f"finalize added unexpected YAML keys to feature.yaml: {unexpected}"


# ---------------------------------------------------------------------------
# CP-2: finalize must NOT touch governance constitutions or lifecycle YAML
# ---------------------------------------------------------------------------

def test_finalize_does_not_touch_constitutions(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize must not create or modify governance constitutions/ files."""
    const_dir = gov_pass / "constitutions"
    const_dir.mkdir()
    sentinel = const_dir / "sentinel.yaml"
    sentinel.write_text("sentinel: true\n", encoding="utf-8")
    mtime_before = sentinel.stat().st_mtime

    _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--confirm"],
        capsys,
    )

    assert sentinel.stat().st_mtime == mtime_before, "finalize must not modify constitutions/ files"


# ---------------------------------------------------------------------------
# CP-6: archive-status — archived feature
# ---------------------------------------------------------------------------

def test_archive_status_archived(capsys: pytest.CaptureFixture, gov_already_complete: Path) -> None:
    """A completed feature returns archived:True from archive-status."""
    exit_code, result = _run(
        ["archive-status", "--governance-repo", str(gov_already_complete), "--feature-id", "lens-dev-done-feature"],
        capsys,
    )
    assert exit_code == 0
    assert result["status"] == "pass"
    assert result["archived"] is True
    assert result["phase"] == "complete"


# ---------------------------------------------------------------------------
# CP-6: archive-status — non-archived feature
# ---------------------------------------------------------------------------

def test_archive_status_not_archived(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """A non-complete feature returns archived:False from archive-status."""
    exit_code, result = _run(
        ["archive-status", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature"],
        capsys,
    )
    assert exit_code == 0
    assert result["status"] == "pass"
    assert result["archived"] is False


# ---------------------------------------------------------------------------
# CP-6: archive-status makes no writes
# ---------------------------------------------------------------------------

def test_archive_status_makes_no_writes(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """archive-status must not write any files."""
    def _mtimes(root: Path) -> dict[str, float]:
        return {str(p.relative_to(root)): p.stat().st_mtime for p in root.rglob("*") if p.is_file()}

    before = _mtimes(gov_pass)
    _run(
        ["archive-status", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature"],
        capsys,
    )
    after = _mtimes(gov_pass)
    assert before == after, f"archive-status modified files: {set(after) - set(before)}"


# ---------------------------------------------------------------------------
# CP-10: finalize requires --confirm or --dry-run
# ---------------------------------------------------------------------------

def test_finalize_requires_confirmation(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize without --confirm or --dry-run returns confirmation_required and does not write."""
    fp = gov_pass / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature" / "feature.yaml"
    mtime_before = fp.stat().st_mtime

    exit_code, result = _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature"],
        capsys,
    )
    assert exit_code != 0
    assert result.get("error") == "confirmation_required"
    assert fp.stat().st_mtime == mtime_before, "finalize must not write without --confirm"


# ---------------------------------------------------------------------------
# CP-7: no final-summary.md references in complete-ops.py
# ---------------------------------------------------------------------------

def test_no_final_summary_references_in_script() -> None:
    """complete-ops.py must not reference 'final-summary.md'."""
    script_path = Path(__file__).resolve().parents[1] / "complete-ops.py"
    text = script_path.read_text(encoding="utf-8")
    assert "final-summary" not in text, (
        "complete-ops.py must not reference 'final-summary.md'; use 'summary.md' only."
    )


# ---------------------------------------------------------------------------
# CP-12: archive-status returns recognized terminal state
# ---------------------------------------------------------------------------

def test_archive_status_terminal_state_recognized(
    capsys: pytest.CaptureFixture, gov_already_complete: Path
) -> None:
    """archive-status returns recognized terminal state for complete-phase feature."""
    exit_code, result = _run(
        ["archive-status", "--governance-repo", str(gov_already_complete), "--feature-id", "lens-dev-done-feature"],
        capsys,
    )
    assert result["archived"] is True
    assert result["phase"] == "complete"
    assert result.get("index_status") == "archived"


# ---------------------------------------------------------------------------
# Prerequisite degradation — missing optional artifact degrades to warning, not failure
# ---------------------------------------------------------------------------

def test_prerequisite_missing_degradation(capsys: pytest.CaptureFixture, gov_pass: Path) -> None:
    """finalize proceeds with warnings when optional document-project artifact is absent."""
    # Remove the optional document-project artifact to exercise the warn/degradation path
    doc_path = (
        gov_pass / "features" / "lens-dev" / "new-codebase" / "lens-dev-test-feature" / "project-documentation.md"
    )
    doc_path.unlink()

    exit_code, result = _run(
        ["finalize", "--governance-repo", str(gov_pass), "--feature-id", "lens-dev-test-feature", "--confirm"],
        capsys,
    )
    assert exit_code == 0
    assert result["status"] == "complete"
    assert "document_project_skipped" in result.get("warnings", []), (
        "Expected 'document_project_skipped' warning when project-documentation.md is absent"
    )
