#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""LENS Workbench v3 — Control Repo Setup.

Bootstraps a new control repo by cloning authority repos (lens.core, governance)
and copying .github from the release module.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def git(*args: str, check: bool = True, cwd: Path | None = None) -> subprocess.CompletedProcess:
    cmd = ["git"] + list(args)
    return subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, check=check)


def clone_or_pull(remote_url: str, local_path: Path, branch: str, label: str, dry_run: bool) -> None:
    git_dir = local_path / ".git"
    is_git = git_dir.is_dir()
    exists = local_path.exists()

    if dry_run:
        if is_git:
            print(f"[INFO] [DRY-RUN] Would pull latest for {label} at {local_path} (branch: {branch})")
        elif exists:
            print(f"[INFO] [DRY-RUN] Would replace existing path and clone {label} -> {local_path} (branch: {branch})")
        else:
            print(f"[INFO] [DRY-RUN] Would clone {label} -> {local_path} (branch: {branch})")
        return

    if is_git:
        print(f"[INFO] Pulling latest for {label} ({local_path})...")
        git("-C", str(local_path), "fetch", "origin", check=False)
        result = git("-C", str(local_path), "checkout", branch, check=False)
        if result.returncode != 0:
            git("-C", str(local_path), "checkout", "-b", branch, f"origin/{branch}", check=False)
        git("-C", str(local_path), "pull", "origin", branch, check=False)
        print(f"[OK]   {label} updated (branch: {branch})")
    else:
        if exists:
            print(f"[WARN] {label} target exists and is not a git repo. Replacing {local_path}")
            shutil.rmtree(local_path, ignore_errors=False)

        print(f"[INFO] Cloning {label} -> {local_path} (branch: {branch})...")
        local_path.parent.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            ["git", "clone", "--branch", branch, remote_url, str(local_path)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"[ERR]  Failed to clone {label}: {result.stderr.strip()}", file=sys.stderr)
            sys.exit(1)
        print(f"[OK]   {label} cloned (branch: {branch})")


def sync_github_from_release(release_path: Path, dest: Path, source_label: str, dry_run: bool) -> None:
    source = release_path / ".github"
    if not source.is_dir():
        print(f"[ERR]  Missing source .github at {source}", file=sys.stderr)
        sys.exit(1)

    if dry_run:
        action = "Would replace" if dest.exists() else "Would create"
        print(f"[INFO] [DRY-RUN] {action} .github from {source_label}")
        return

    if dest.is_dir():
        if (dest / ".git").is_dir():
            print("[WARN] .github is a git repo in control repo. Removing before copy")
        else:
            print(f"[INFO] Replacing existing .github at {dest}")
        shutil.rmtree(dest)

    shutil.copytree(source, dest)
    print(f"[OK]   .github copied from {source_label}")


def governance_setup_file(project_root: Path) -> Path:
    return project_root / ".lens" / "governance-setup.yaml"


def write_governance_setup_file(
    project_root: Path,
    governance_path: Path,
    governance_url: str,
    timestamp: str,
) -> Path:
    setup_path = governance_setup_file(project_root)
    setup_path.parent.mkdir(parents=True, exist_ok=True)
    setup_path.write_text(
        f"# Generated by setup-control-repo.py — {timestamp}\n"
        f"governance_repo_path: \"{governance_path}\"\n"
        f"governance_remote_url: \"{governance_url}\"\n",
        encoding="utf-8",
    )
    return setup_path


def ensure_github_repo_exists(base_url: str, owner: str, repo: str, remote_url: str, dry_run: bool) -> None:
    repo_full = f"{owner}/{repo}"
    if dry_run:
        print(f"[INFO] [DRY-RUN] Would verify {repo_full} exists")
        return

    result = subprocess.run(
        ["git", "ls-remote", remote_url, "HEAD"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(f"[INFO] {repo_full} is available")
        return

    print(f"[WARN] {repo_full} is missing or inaccessible. Attempting to create it as private repo.")
    gh_check = subprocess.run(["which", "gh"], capture_output=True)
    if gh_check.returncode != 0:
        print(f"[ERR]  GitHub CLI (gh) required to auto-create {repo_full}. Install gh or create the repo manually.", file=sys.stderr)
        sys.exit(1)

    env: dict = {}
    import os
    env = dict(os.environ)
    try:
        from urllib.parse import urlparse
        parsed = urlparse(base_url)
        if parsed.hostname and parsed.hostname != "github.com":
            env["GH_HOST"] = parsed.hostname
            print(f"[INFO] Using GitHub host {parsed.hostname} for repository creation")
        else:
            env.pop("GH_HOST", None)
    except Exception:
        pass

    result = subprocess.run(
        ["gh", "repo", "create", repo_full, "--private", "--add-readme",
         "--description", "LENS governance repository", "--disable-issues"],
        env=env, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"[ERR]  Failed to create private repository {repo_full}: {result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)

    print(f"[OK]   Created private repository {repo_full}")

    # Verify reachable
    verify = subprocess.run(["git", "ls-remote", remote_url, "HEAD"], capture_output=True, text=True)
    if verify.returncode != 0:
        print(f"[ERR]  Repository {repo_full} was created but is still not reachable at {remote_url}", file=sys.stderr)
        sys.exit(1)


def resolve_clone_branch(remote_url: str, preferred: str, label: str, dry_run: bool) -> str:
    if dry_run:
        return preferred

    result = subprocess.run(
        ["git", "ls-remote", "--heads", remote_url, preferred],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        return preferred

    result2 = subprocess.run(
        ["git", "ls-remote", "--symref", remote_url, "HEAD"],
        capture_output=True, text=True,
    )
    for line in result2.stdout.splitlines():
        m = re.search(r"refs/heads/([^\t ]+)", line)
        if m:
            default = m.group(1)
            print(f"[WARN] {label} does not have branch '{preferred}'. Using default branch '{default}' instead.")
            return default

    print(f"[ERR]  Unable to resolve default branch for {label}", file=sys.stderr)
    sys.exit(1)


def ensure_gitignore_entries(root: Path, dry_run: bool) -> None:
    entries = [
        ".lens/",
        ".lens/personal/",
        ".github/",
        "lens.core/",
        "TargetProjects/",
    ]
    gi = root / ".gitignore"
    if dry_run:
        print(f"[INFO] [DRY-RUN] Would update .gitignore in {root}")
        return

    existing: set[str] = set()
    if gi.is_file():
        existing = set(gi.read_text(encoding="utf-8").splitlines())
    else:
        gi.touch()
        print(f"[INFO] Created .gitignore")

    added = 0
    with open(gi, "a", encoding="utf-8") as fh:
        for entry in entries:
            if entry not in existing:
                fh.write(f"{entry}\n")
                print(f"[INFO] Added '{entry}' to .gitignore")
                added += 1

    if added == 0:
        print("[OK]   .gitignore already contains required entries")
    else:
        print(f"[OK]   .gitignore updated with required entries")


# ---------------------------------------------------------------------------
# Wizard
# ---------------------------------------------------------------------------

def prompt(text: str, default: str) -> str:
    try:
        val = input(f"  {text} [{default}]: ").strip()
    except (KeyboardInterrupt, EOFError):
        print("\n[cancelled]")
        sys.exit(0)
    return val if val else default


def yn(text: str, default: bool = True) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    try:
        val = input(f"  {text} {suffix}: ").strip().lower()
    except (KeyboardInterrupt, EOFError):
        print("\n[cancelled]")
        sys.exit(0)
    if not val:
        return default
    return val.startswith("y")


def detect_github_username() -> str:
    # Try 'gh' CLI
    result = subprocess.run(["gh", "api", "user", "--jq", ".login"], capture_output=True, text=True)
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    # Try git config
    result2 = subprocess.run(["git", "config", "user.name"], capture_output=True, text=True)
    if result2.returncode == 0 and result2.stdout.strip():
        return result2.stdout.strip()
    return ""


def derive_governance_repo(control_dir: Path) -> str:
    name = control_dir.name
    if name.endswith(".src"):
        name = name[:-4] + ".bmad"
    return f"{name}.governance"


def run_wizard(defaults: dict) -> dict:  # returns filled-in config
    print()
    print("+--------------------------------------------------------------+")
    print("|       LENS Workbench v3 -- Control Repo Setup Wizard         |")
    print("+--------------------------------------------------------------+")
    print()
    print("  This wizard will bootstrap your control repo by:")
    print("    1. Cloning the LENS release module (read-only)")
    print("    2. Copying the GitHub Copilot adapter (.github/)")
    print("    3. Cloning (or creating) your governance repo")
    print("    4. Setting up output directories and LENS_VERSION")
    print()
    print("  Press Enter to accept defaults shown in [brackets].")
    print()

    cfg = dict(defaults)

    # Step 1: Control repo directory
    print("Step 1: Control Repo Directory")
    cfg["project_root"] = Path(prompt("Control repo directory", str(cfg["project_root"])))
    if not cfg["project_root"].is_absolute():
        cfg["project_root"] = Path.cwd() / cfg["project_root"]
    cfg["governance_repo"] = derive_governance_repo(cfg["project_root"])
    cfg["governance_path"] = cfg["project_root"] / "TargetProjects" / "lens" / cfg["governance_repo"]
    print()

    # Step 2: GitHub account
    print("Step 2: GitHub Account")
    detected = detect_github_username()
    if detected:
        print(f"  Detected: {detected}")
    cfg["org"] = prompt("GitHub org or username", detected or "your-username")
    print()

    # Step 3: GitHub server
    print("Step 3: GitHub Server")
    if yn("Use github.com?", default=True):
        cfg["base_url"] = "https://github.com"
    else:
        cfg["base_url"] = prompt("Enterprise GitHub URL", "https://github.company.com")
    print()

    # Step 4: Release repo
    print("Step 4: Release Repository")
    cfg["release_repo"] = prompt("Release repo name", cfg["release_repo"])
    cfg["release_branch"] = prompt("Release repo branch", cfg["release_branch"])
    cfg["release_org"] = prompt("Release repo owner", cfg["org"])
    print()

    # Step 5: Governance repo
    print("Step 5: Governance Repository")
    print(f"  Auto-derived from control repo name: {cfg['governance_repo']}")
    cfg["governance_repo"] = prompt("Governance repo name", cfg["governance_repo"])
    cfg["governance_branch"] = prompt("Governance repo branch", cfg["governance_branch"])
    cfg["governance_org"] = prompt("Governance repo owner", cfg["org"])
    cfg["governance_path"] = Path(prompt("Local clone path", str(cfg["project_root"] / "TargetProjects" / "lens" / cfg["governance_repo"])))
    if not cfg["governance_path"].is_absolute():
        cfg["governance_path"] = cfg["project_root"] / cfg["governance_path"]
    print()

    # Step 6: Confirm
    print("Step 6: Review & Confirm")
    print()
    print(f"    Base URL:         {cfg['base_url']}")
    print(f"    Control repo:     {cfg['project_root']}")
    print()
    print(f"    Release repo:     {cfg['release_org']}/{cfg['release_repo']} (branch: {cfg['release_branch']})")
    print(f"      -> clone to:     {cfg['release_repo']}/")
    print(f"      -> .github:      copied from release repo")
    print()
    print(f"    Governance repo:  {cfg['governance_org']}/{cfg['governance_repo']} (branch: {cfg['governance_branch']})")
    print(f"      -> clone to:     {cfg['governance_path']}/")
    print()

    if not yn("Proceed with setup?", default=True):
        print()
        print("  Setup cancelled.")
        sys.exit(0)
    print()
    return cfg


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="LENS Workbench v3 — Control Repo Setup"
    )
    parser.add_argument("--org", default="")
    parser.add_argument("--control-dir", default="")
    parser.add_argument("--release-org", default="")
    parser.add_argument("--release-repo", default="lens.core")
    parser.add_argument("--release-branch", default="beta")
    parser.add_argument("--governance-org", default="")
    parser.add_argument("--governance-repo", default="")
    parser.add_argument("--governance-branch", default="main")
    parser.add_argument("--governance-path", default="")
    parser.add_argument("--base-url", default="https://github.com")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    dry_run = args.dry_run

    # Determine project root
    script_dir = Path(__file__).resolve().parent
    try:
        result = subprocess.run(
            ["git", "-C", str(script_dir), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        )
        project_root = Path(result.stdout.strip())
    except Exception:
        _cwd = Path.cwd()
        project_root = (
            _cwd if (_cwd / "lens.core").exists()
            else next(p for p in script_dir.parents if (p / "lens.core").exists())
        )

    if args.control_dir:
        project_root = Path(args.control_dir).resolve()

    gov_repo_default = derive_governance_repo(project_root)
    gov_path_default = project_root / "TargetProjects" / "lens" / gov_repo_default

    defaults = {
        "project_root": project_root,
        "org": args.org,
        "base_url": args.base_url,
        "release_repo": args.release_repo,
        "release_branch": args.release_branch,
        "release_org": args.release_org or args.org,
        "governance_repo": args.governance_repo or gov_repo_default,
        "governance_branch": args.governance_branch,
        "governance_org": args.governance_org or args.org,
        "governance_path": Path(args.governance_path) if args.governance_path else gov_path_default,
    }

    # Wizard mode if no meaningful params given
    has_params = any([args.org, args.control_dir, args.release_org, args.governance_org,
                      args.governance_repo, args.release_repo != "lens.core",
                      args.base_url != "https://github.com"])

    if has_params:
        # Validate minimum
        if not args.org and not args.release_org and not args.governance_org:
            print("[ERR]  --org is required (or specify --release-org, --governance-org individually)", file=sys.stderr)
            print()
            print("Usage: uv run scripts/setup-control-repo.py --org <github-org-or-user>")
            return 1
        cfg = defaults
        if not cfg["release_org"]:
            cfg["release_org"] = cfg["org"]
        if not cfg["governance_org"]:
            cfg["governance_org"] = cfg["org"]
    else:
        cfg = run_wizard(defaults)

    project_root = cfg["project_root"]
    base_url = cfg["base_url"]
    release_org = cfg["release_org"]
    release_repo = cfg["release_repo"]
    release_branch = cfg["release_branch"]
    governance_org = cfg["governance_org"]
    governance_repo = cfg["governance_repo"]
    governance_branch = cfg["governance_branch"]
    governance_path = cfg["governance_path"]

    print()
    print("LENS Workbench v3 - Control Repo Setup")
    print()
    print(f"Base URL: {base_url}")
    print(f"Root:     {project_root}")
    print()

    if dry_run:
        print("[WARN] Dry run mode: no changes will be made")
        print()

    # 1. Release repo
    release_url = f"{base_url}/{release_org}/{release_repo}.git"
    release_local = project_root / release_repo
    clone_or_pull(release_url, release_local, release_branch, f"{release_org}/{release_repo}", dry_run)

    # 2. Sync .github
    copilot_path = project_root / ".github"
    sync_github_from_release(release_local, copilot_path, f"{release_org}/{release_repo}/.github", dry_run)

    # 3. Governance repo
    gov_url = f"{base_url}/{governance_org}/{governance_repo}.git"
    ensure_github_repo_exists(base_url, governance_org, governance_repo, gov_url, dry_run)
    gov_clone_branch = resolve_clone_branch(gov_url, governance_branch, f"{governance_org}/{governance_repo}", dry_run)
    clone_or_pull(gov_url, governance_path, gov_clone_branch, f"{governance_org}/{governance_repo}", dry_run)

    # 4. Output directories
    if not dry_run:
        for rel in ["docs/lens-work/initiatives", ".lens", ".lens/personal"]:
            (project_root / rel).mkdir(parents=True, exist_ok=True)
        print("[OK]   Output directory structure verified")
    else:
        print("[INFO] [DRY-RUN] Would create docs/lens-work/initiatives, .lens, and .lens/personal")

    # 4b. .lens/governance-setup.yaml
    if not dry_run:
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        gov_setup = write_governance_setup_file(project_root, governance_path, gov_url, ts)
        print(f"[OK]   {gov_setup.relative_to(project_root)} written")
    else:
        print("[INFO] [DRY-RUN] Would write .lens/governance-setup.yaml")

    # 5. LENS_VERSION
    if not dry_run:
        lifecycle_path = release_local / "_bmad/lens-work/lifecycle.yaml"
        if not lifecycle_path.is_file():
            print(f"[ERR]  lifecycle.yaml not found at {lifecycle_path}", file=sys.stderr)
            return 1
        schema_version = ""
        for line in lifecycle_path.read_text(encoding="utf-8").splitlines():
            if re.match(r"^\s*schema_version\s*:", line):
                schema_version = line.split(":", 1)[1].strip()
                break
        if not schema_version:
            print(f"[ERR]  schema_version not found in {lifecycle_path}", file=sys.stderr)
            return 1
        version_str = f"{schema_version}.0.0"
        lens_version_path = project_root / ".lens" / "LENS_VERSION"
        lens_version_path.parent.mkdir(parents=True, exist_ok=True)
        lens_version_path.write_text(version_str, encoding="utf-8")
        print(f"[OK]   .lens/LENS_VERSION written: {version_str}")
    else:
        print("[INFO] [DRY-RUN] Would write .lens/LENS_VERSION")

    # 6. .gitignore
    ensure_gitignore_entries(project_root, dry_run)

    # Summary
    print()
    print("Setup Complete")
    print()
    print(f"  {release_org}/{release_repo} -> {release_repo}/    (branch: {release_branch})")
    print(f"  .github  <--  {release_repo}/.github")
    print(f"  {governance_org}/{governance_repo} -> {governance_path}/  (branch: {gov_clone_branch if not dry_run else governance_branch})")
    print()
    print(f"GitHub Copilot adapter is installed from {release_repo}/.github.")
    print("No further setup is needed if GitHub Copilot is your only IDE.")
    print()
    print("For non-Copilot IDEs, run the module installer:")
    print(f"  uv run lens.core/_bmad/lens-work/scripts/install.py --ide cursor")
    print(f"  uv run lens.core/_bmad/lens-work/scripts/install.py --all-ides")
    print()
    print("Next Steps:")
    print("  1. Store your GitHub PAT (run in terminal, not in AI chat):")
    print(f"     uv run {release_repo}/_bmad/lens-work/scripts/store-github-pat.py")
    print("  2. Open VS Code + GitHub Copilot Chat and run:")
    print("     /new-project")
    print("     (or /new-domain and /new-service for step-by-step scaffolding)")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
