#Requires -Version 5.1
<#
.SYNOPSIS
    LENS Workbench — GitHub PAT Storage Script

.DESCRIPTION
    Securely stores GitHub Personal Access Tokens outside of any LLM/AI chat context.
    PATs are NEVER entered into Copilot, Claude, or any other AI assistant.

.USAGE
    cd <project-root>
    .\\_bmad\\lens-work\\scripts\\store-github-pat.ps1

.OUTPUTS
    _bmad-output/lens-work/personal/github-credentials.yaml
    (gitignored — never committed)
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve Paths ────────────────────────────────────────────
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot  = Resolve-Path (Join-Path $ScriptDir '../../..') | Select-Object -ExpandProperty Path
$CredFile     = Join-Path $ProjectRoot '_bmad-output\lens-work\personal\github-credentials.yaml'
$InventoryFile= Join-Path $ProjectRoot '_bmad-output\lens-work\repo-inventory.yaml'

# ── Banner ───────────────────────────────────────────────────
Write-Host ""
Write-Host "🔐 LENS Workbench — GitHub PAT Setup" -ForegroundColor Cyan
Write-Host ""  # blank line after banner
Write-Host "════════════════════════════════════" -ForegroundColor DarkGray
Write-Host ""
Write-Host "⚠️  SECURITY: " -ForegroundColor Yellow -NoNewline
Write-Host "PATs entered here are stored ONLY in:"
Write-Host "   $CredFile" -ForegroundColor DarkYellow
Write-Host "   This file is gitignored and never committed."
Write-Host ""

# ── Ensure output directory ──────────────────────────────────
$CredDir = Split-Path -Parent $CredFile
if (-not (Test-Path $CredDir)) {
    New-Item -ItemType Directory -Path $CredDir -Force | Out-Null
}

# ── Detect GitHub domains ────────────────────────────────────
$GithubDomains = @()

if (Test-Path $InventoryFile) {
    $InventoryContent = Get-Content $InventoryFile -Raw -ErrorAction SilentlyContinue
    $RegexMatches = [regex]::Matches($InventoryContent, 'github\.[a-zA-Z0-9._-]+')
    $Detected = $RegexMatches.Value | Sort-Object -Unique
    foreach ($d in $Detected) {
        if ($d -notin $GithubDomains) { $GithubDomains += $d }
    }
}

# Always ensure github.com is present
if ('github.com' -notin $GithubDomains) {
    $GithubDomains = @('github.com') + $GithubDomains
}

Write-Host "Detected GitHub domain(s):" -ForegroundColor White
foreach ($d in $GithubDomains) {
    Write-Host "  • $d" -ForegroundColor Cyan
}
Write-Host ""

# Allow adding extra domains
$ExtraDomain = Read-Host "Add additional GitHub Enterprise domain? (press Enter to skip)"
if ($ExtraDomain.Trim()) {
    $GithubDomains += $ExtraDomain.Trim()
}
Write-Host ""

# ── Initialize credentials file ─────────────────────────────
$Timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$Header = @"
# GitHub Personal Access Tokens
# Generated by: store-github-pat.ps1
# Date: $Timestamp
# GITIGNORED -- never committed -- local machine only
#
# Required scopes: repo, read:org
# Regenerate at:
#   GitHub SaaS:       https://github.com/settings/tokens
#   GitHub Enterprise: https://{your-domain}/settings/tokens

"@

Set-Content -Path $CredFile -Value $Header -Encoding UTF8

# ── Collect PAT per domain ────────────────────────────────────
$Stored  = 0
$Skipped = 0

foreach ($Domain in $GithubDomains) {
    Write-Host (("─── {0} " -f $Domain) + ("─" * [Math]::Max(0, 40 - $Domain.Length))) -ForegroundColor DarkGray
    Write-Host "  Domain: " -NoNewline; Write-Host $Domain -ForegroundColor Cyan

    if ($Domain -eq 'github.com') {
        $PatUrl     = 'https://github.com/settings/tokens'
        $DomainType = 'github.com'
    } else {
        $PatUrl     = "https://$Domain/settings/tokens"
        $DomainType = 'github_enterprise'
    }

    Write-Host "  Generate token at: " -NoNewline
    Write-Host $PatUrl -ForegroundColor Cyan
    Write-Host "  Required scopes:   " -NoNewline
    Write-Host "repo, read:org" -ForegroundColor Yellow
    Write-Host ""

    $SecurePat = Read-Host "  Enter PAT for $Domain (press Enter to skip)" -AsSecureString
    $PatPlain  = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePat))
    Write-Host ""

    if ([string]::IsNullOrEmpty($PatPlain)) {
        Write-Host "  ⏭  Skipped" -ForegroundColor Yellow
        $Skipped++
    } else {
        $Entry = @"
${Domain}:
  token: $PatPlain
  created_at: "$Timestamp"
  type: $DomainType

"@
        Add-Content -Path $CredFile -Value $Entry -Encoding UTF8
        Write-Host "  ✅ Stored" -ForegroundColor Green
        $Stored++
    }
    Write-Host ""
}

# ── Summary ───────────────────────────────────────────────────
Write-Host "════════════════════════════════════" -ForegroundColor DarkGray
Write-Host "Summary" -ForegroundColor White
Write-Host "  ✅ Stored:  $Stored token(s)" -ForegroundColor Green
Write-Host "  ⏭  Skipped: $Skipped domain(s)" -ForegroundColor Yellow
Write-Host ""

if ($Stored -gt 0) {
    Write-Host "PATs stored at:" -ForegroundColor Green
    Write-Host "  $CredFile" -ForegroundColor DarkYellow
    Write-Host ""

    # Open in VS Code if available
    $CodePath = Get-Command code -ErrorAction SilentlyContinue
    if ($CodePath) {
        Write-Host "Opening credentials file in VS Code..."
        & code $CredFile
    }

    Write-Host ""
    Write-Host "✅ PAT setup complete! You can now close this terminal." -ForegroundColor Green
} else {
    Write-Host "No PATs were stored. Run this script again when ready." -ForegroundColor Yellow
}

Write-Host ""
