#!/usr/bin/env bash
# ============================================================
# LENS Workbench — GitHub PAT Storage Script
# store-github-pat.sh
#
# PURPOSE:
#   Securely stores GitHub Personal Access Tokens outside of
#   any LLM/AI chat context — PATs are NEVER entered into Copilot
#   or any other AI assistant.
#
# USAGE:
#   cd <project-root>
#   bash _bmad/lens-work/scripts/store-github-pat.sh
#
# OUTPUT:
#   _bmad-output/lens-work/personal/github-credentials.yaml
#   (gitignored — never committed)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
CREDENTIALS_FILE="${PROJECT_ROOT}/_bmad-output/lens-work/personal/github-credentials.yaml"
INVENTORY_FILE="${PROJECT_ROOT}/_bmad-output/lens-work/repo-inventory.yaml"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

echo ""
echo -e "${BOLD}${CYAN}🔐 LENS Workbench — GitHub PAT Setup${RESET}"
echo "════════════════════════════════════"
echo ""
echo -e "${YELLOW}⚠️  SECURITY: PATs entered here are stored ONLY in:${RESET}"
echo "   ${CREDENTIALS_FILE}"
echo "   This file is gitignored and never committed."
echo ""

# ── Check for environment variables ─────────────────────────
if [[ -n "${GITHUB_PAT:-}" || -n "${GH_TOKEN:-}" ]]; then
  ENV_VAR_NAME=""
  if [[ -n "${GITHUB_PAT:-}" ]]; then
    ENV_VAR_NAME="GITHUB_PAT"
  else
    ENV_VAR_NAME="GH_TOKEN"
  fi
  echo -e "${GREEN}✅ ${ENV_VAR_NAME} environment variable detected.${RESET}"
  echo -e "   The promote-branch script will use this automatically."
  echo ""
  echo -e "   Do you also want to store it in the credentials file? ${BOLD}(y/N)${RESET}"
  read -r STORE_ENV_PAT
  if [[ ! "$STORE_ENV_PAT" =~ ^[yY] ]]; then
    echo ""
    echo -e "${GREEN}${BOLD}✅ Using ${ENV_VAR_NAME} environment variable. No file changes needed.${RESET}"
    echo -e "   promote-branch.sh will pick up the PAT from the environment."
    echo ""
    exit 0
  fi
  echo ""
fi

# ── Ensure output directory exists ──────────────────────────
mkdir -p "$(dirname "${CREDENTIALS_FILE}")"

# ── Detect GitHub domains ────────────────────────────────────
GITHUB_DOMAINS=()

# Try to detect from repo inventory
if [[ -f "${INVENTORY_FILE}" ]]; then
  while IFS= read -r domain; do
    [[ -n "${domain}" ]] && GITHUB_DOMAINS+=("${domain}")
  done < <(grep -oP '(?<=github\.)[a-zA-Z0-9._-]+' "${INVENTORY_FILE}" 2>/dev/null \
    | sed 's/^/github./' | sort -u || true)
fi

# Always include github.com as a default
if [[ ${#GITHUB_DOMAINS[@]} -eq 0 ]]; then
  GITHUB_DOMAINS=("github.com")
else
  # Ensure github.com is in the list
  if ! printf '%s\n' "${GITHUB_DOMAINS[@]}" | grep -q "^github\.com$"; then
    GITHUB_DOMAINS=("github.com" "${GITHUB_DOMAINS[@]}")
  fi
fi

echo -e "${BOLD}Detected GitHub domain(s):${RESET}"
for d in "${GITHUB_DOMAINS[@]}"; do
  echo "  • ${d}"
done
echo ""

# Allow adding extra domains
echo -e "Add additional GitHub Enterprise domain? ${CYAN}[Enter domain or press Enter to skip]${RESET}"
read -r EXTRA_DOMAIN
if [[ -n "${EXTRA_DOMAIN}" ]]; then
  GITHUB_DOMAINS+=("${EXTRA_DOMAIN}")
fi
echo ""

# ── Initialize credentials file ─────────────────────────────
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -Iseconds 2>/dev/null || echo "$(date)")

cat > "${CREDENTIALS_FILE}" << YAML_HEADER
# GitHub Personal Access Tokens
# Generated by: store-github-pat.sh
# Date: ${TIMESTAMP}
# GITIGNORED — never committed — local machine only
#
# Required scopes: repo, read:org
# Regenerate at:
#   GitHub SaaS:       https://github.com/settings/tokens
#   GitHub Enterprise: https://{your-domain}/settings/tokens

YAML_HEADER

# ── Collect PAT per domain ────────────────────────────────────
STORED=0
SKIPPED=0

# Note: use arithmetic assignment (not ((var++))) to avoid set -e false-exit
# when the pre-increment value is 0 (arithmetic returns exit code = old value).

for DOMAIN in "${GITHUB_DOMAINS[@]}"; do
  echo -e "${BOLD}─── ${DOMAIN} ───────────────────────────────────────${RESET}"

  # Classify domain type
  if [[ "${DOMAIN}" == "github.com" ]]; then
    PAT_URL="https://github.com/settings/tokens"
    DOMAIN_TYPE="github.com"
  else
    PAT_URL="https://${DOMAIN}/settings/tokens"
    DOMAIN_TYPE="github_enterprise"
  fi

  echo -e "  Generate token at: ${CYAN}${PAT_URL}${RESET}"
  echo -e "  Required scopes:   ${YELLOW}repo, read:org${RESET}"
  echo ""
  echo -e "  Enter PAT for ${BOLD}${DOMAIN}${RESET} (or press Enter to skip):"
  read -rs PAT_VALUE
  echo ""

  if [[ -z "${PAT_VALUE}" ]]; then
    echo -e "  ${YELLOW}⏭  Skipped${RESET}"
    SKIPPED=$((SKIPPED + 1))
  else
    # Basic validation — GitHub PATs start with ghp_, github_pat_, or ghs_
    if [[ "${PAT_VALUE}" =~ ^(ghp_|github_pat_|ghs_|glpat-|[a-zA-Z0-9]{40,}) ]]; then
      cat >> "${CREDENTIALS_FILE}" << YAML_ENTRY
${DOMAIN}:
  token: ${PAT_VALUE}
  created_at: "${TIMESTAMP}"
  type: ${DOMAIN_TYPE}

YAML_ENTRY
      echo -e "  ${GREEN}✅ Stored${RESET}"
      STORED=$((STORED + 1))
    else
      echo -e "  ${RED}⚠️  Unexpected PAT format — storing anyway...${RESET}"
      cat >> "${CREDENTIALS_FILE}" << YAML_ENTRY
${DOMAIN}:
  token: ${PAT_VALUE}
  created_at: "${TIMESTAMP}"
  type: ${DOMAIN_TYPE}

YAML_ENTRY
      STORED=$((STORED + 1))
    fi
  fi
  echo ""
done

# ── Summary ───────────────────────────────────────────────────
echo "════════════════════════════════════"
echo -e "${BOLD}Summary${RESET}"
echo "  ✅ Stored:  ${STORED} token(s)"
echo "  ⏭  Skipped: ${SKIPPED} domain(s)"
echo ""

if [[ ${STORED} -gt 0 ]]; then
  echo -e "${GREEN}PATs stored at:${RESET}"
  echo "  ${CREDENTIALS_FILE}"
  echo ""

  # Open in VS Code if available
  if command -v code &>/dev/null; then
    echo -e "Opening credentials file in VS Code..."
    code "${CREDENTIALS_FILE}"
  fi

  echo -e "${GREEN}${BOLD}✅ PAT setup complete! You can now close this terminal.${RESET}"
else
  echo -e "${YELLOW}No PATs were stored. Run this script again when ready.${RESET}"
fi
echo ""
